eventFinderApp/urls.py
from django.urls import path
from . import views

app_name = 'eventFinderApp'

urlpatterns = [
    # event-finder/
    path('', views.IndexView.as_view(), name='index'),
    # event-finder/1
    path('<int:pk>/', views.EventView.as_view(), name='event'),
    # event-finder/my-account
    path('my-account/', views.account, name='account'),
    # event-finder/add-event
    path('add-event/', views.add_event, name='add_event'),  
]

eventFinderProject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.i18n import JavaScriptCatalog
from rest_framework import routers
from eventFinderApp import viewsets
from rest_framework.authtoken import views
from users import viewsets as UserViewsets

router = routers.DefaultRouter()
router.register(r'events', viewsets.EventViewSet)
router.register(r'users', UserViewsets.CustomUserViewSet)

urlpatterns = [
    path('event-finder/', include('eventFinderApp.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('api/', include(router.urls)),
    path(r'api-auth-token/', views.obtain_auth_token),
    path('jsi18n', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

users/urls.py
from . import views
from django.urls import include, path

app_name = 'users'

urlpatterns = [
path('event-finder/', include('eventFinderApp.urls')),
path('register/', views.Register.as_view(), name='register'),

]

eventFinderApp/models.py
from django.conf import settings
from django.db import models

class Event(models.Model):
    title = models.CharField(max_length=200)
    location = models.CharField(max_length=200)
    venue = models.CharField(max_length=200)
    start_time = models.DateTimeField('start time and date')
    end_time = models.DateTimeField('end time and date')
    categories = models.ManyToManyField('Category', related_name='events')
    host = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Account(models.Model):
    first_name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    email = models.EmailField()

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
  # add additional fields in here

  def __str__(self):
    return self.email

eventFinderApp/forms.py
from django.forms import ModelForm, SplitDateTimeField
from .models import Event, Category, Account
from django.contrib.admin import widgets



class EventForm(ModelForm):
    start_time = SplitDateTimeField(widget=widgets.AdminSplitDateTime())
    end_time = SplitDateTimeField(widget=widgets.AdminSplitDateTime())

    class Meta:
        model = Event
        exclude = ['host']
        

class AccountForm(ModelForm):
    class Meta:
        model = Account
        fields = [
            'first_name',
            'surname',
            'email'
        ]

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

  class Meta(UserCreationForm):
    model = CustomUser
    fields = ('username', 'email')

class CustomUserChangeForm(UserChangeForm):

  class Meta:
    model = CustomUser
    fields = ('username', 'email')

eventFinderApp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.shortcuts import render
from .models import Event, Account
from .forms import EventForm, AccountForm
from django.contrib.auth.decorators import login_required

class IndexView(generic.ListView):
    template_name = 'eventFinderApp/index.html'
    context_object_name = 'events_list'

    def get_queryset(self):
        '''Return the events.'''
        return Event.objects.all()


class EventView(generic.DetailView):
    model = Event
    template_name = 'eventFinderApp/event.html'

class AccountView(generic.DetailView):
    model = Account
    template_name = 'eventFinderApp/account.html'

def account(request):
    accountform = AccountForm()
    return render(request, 'eventFinderApp/account.html', {'accountform': accountform})

@login_required(login_url='login')
def add_event(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = EventForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            event = form.save(commit=False)
            event.host = request.user
            event.save()
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            # return HttpResponseRedirect('/thanks/')
            
            return HttpResponseRedirect(reverse('eventFinderApp:index'))
        return render(request, 'eventFinderApp/newEventForm.html', {'eventform': form})
    # if a GET (or any other method) we'll create a blank form
    else:
        eventform = EventForm()
        return render(request, 'eventFinderApp/newEventForm.html', {'eventform': eventform})

users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from .forms import CustomUserCreationForm

class Register(generic.CreateView):
  form_class = CustomUserCreationForm
  success_url = reverse_lazy('login')
  template_name = 'registration/register.html'

eventFinderApp/templates/eventFinderApp/account.html
{% extends "base.html" %}

{% block content %}

<h3>Profile</h3>
<p>Username: {{ user.username }}</p>
<p>First Name: {{ user.first_name }}</p>
<p>Last Name: {{ user.last_name }}</p>
<p>Email: {{ user.email }}</p>


<h3>Your events:</h3>
    {% if events_list %}
        {% for event in events_list %}
            {% include "./detailsBox.html" with event=event %}
        {% endfor %}
    {% else %}
        <p>You're not hosting any events.</p>
    {% endif %}


{% endblock %}

eventFinderApp/templates/eventFinderApp/base.html
{% load static %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>EventFinda</title>
        <meta name="description" content="">
        <meta name="author" content="Hayley van Waas">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'eventFinderApp/style.css' %}">
    </head>

    <body>
        <header>
            <div>
                <h1>EventFinda</h1>
                <h2>Find free events near you!</h2>
            </div>
            {% include './nav.html' %}
        </header>

        {% block content %}{% endblock %}
    </body>
</html>

eventFinderApp/templates/eventFinderApp/detailsBox.html
<section class = "container col-sm-12 col-md-5 col-lg-4">
  <div class="card">
    <img class="card-img-top img-thumbnail" src="https://images.app.goo.gl/ELNy9hRdJgzSSY4e7" alt="event image">
      <div class="card-body">
        <h5 class="card-title">{{ event.title }}</h5>
        <p class="card-text">{{ event.start_time }}</p>
                  
                  <ul class="list-group list-group-flush">
                      {% for cat in event.categories.all %}
                      <li class="list-group-item">{{ cat.name }}</li>
                      {% endfor %}
                  </ul>
            
            <div class="card-body">
            <a href="{% url 'eventFinderApp:event' event.id %}" class="btn">+ sign up for this event</a>
            <a href="{% url 'eventFinderApp:event' event.id %}" class="btn">+ more details</a>
      </div>
          </div>
  </div>
</section>

eventFinderApp/templates/eventFinderApp/event.html
{% extends "base.html" %}

{% block content %}

<h2>{{ event.title }}</h2>
<p>{{ event.location }}</p>
<p>Starts at: {{ event.start_time }}</p>
<p>Ends at: {{ event.end_time }}</p>
<p>Category:
  {% for cat in event.categories.all %}
  <p>{{ cat.name }}</p>
        {% endfor %}

        <h3>Hosted by:{{event.host.username}}</h3>

{% endblock %}

eventFinderApp/templates/eventFinderApp/index.html
{% extends "base.html" %}

{% block content %}

    <a href="{% url 'eventFinderApp:add_event' %}"><button id="new-event">+ Event</button></a>

    <h3>See what's on!</h3>
    <div class="row">
    {% if events_list %}
        {% for event in events_list %}
            {% include "./detailsBox.html" with event=event %}
        {% endfor %}
    {% else %}
        <p>No events are available.</p>
    {% endif %}
</div>
{% endblock %}

eventFinderApp/templates/eventFinderApp/newEventForm.html
{% extends "base.html" %}

{% block content %}

<h2>Add an Event</h2>


<form action="" method="post">
    {{ eventform.media }}
    {% csrf_token %}
    {{ eventform.as_p }}
    <button type="submit" value="Submit" class="btn">Submit</button>
</form>

{% endblock %}

templates/base.html
{% load staticfiles %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>WAEventFinda</title>
        <meta name="description" content="">
        <meta name="author" content="Hayley van Waas">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>
        <script type="text/javascript" src="{% static '/admin/js/core.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static '/admin/css/widgets.css' %}">
        <style>
                .calendar>table>caption{caption-side:unset}
            </style><!--caption fix for bootstrap4-->   
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        
    </head>

    <body>
        <header>
                {% include './nav.html' %}
        </header>
            <div class = container>
                <div class= "row">
                    <h1 class="neon green fluid col-sm-12 col-md-12">WA Event Finda</h1>
                    <h2 class = "col-sm-12 col-md-12">Find free events near you!</h2>
                </div>
            </div>

        {% block content %}
        {% endblock %}

        {% include './footer.html' %}
            <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
     
</body>
</html>

templates/footer.html
<footer class="container-fluid">
    <div class="row">
        <div class="col">
             <p class="text-center">Copyright © 2019 Madelynn Braun. All Rights Reserved.</p></div>
       </div>
</footer>

templates/nav.html
<nav class="navbar navbar-expand-md navbar-dark bg-#000">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03"> 
          {% if user.is_authenticated %}
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
              <li class="nav-item active">
                      <a class="nav-link" href="{% url 'eventFinderApp:index' %}">Home</a>            </li>
              <li class="nav-item">
                      <a class="nav-link" href="{% url 'eventFinderApp:account' %}">Hi {{ user.username }}</a>            </li>
              <li class="nav-item">
                      <a class="nav-link" href="{% url 'logout' %}">logout</a>        </li>   
              </ul>
                {% else %}
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                            <a class="nav-link" href="{% url 'eventFinderApp:index' %}">Home</a>            </li>
                    <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">login</a>        </li>   
                    </ul>
                {% endif %}   
            <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>